### PR TITLE
Support scala 3.0.0 final

### PR DESCRIPTION
**Pull request by timothyklim**

### CODE REVIEW

**Comment by timothyklim** [comment]
Blocked by https://github.com/scalatest/scalatest/issues/2027

**Comment by timothyklim** [comment]
protobuf-runtime-scala_sjs1_2.12 0.8.12 is not available

```
[error] sbt.librarymanagement.ResolveException: Error downloading com.thesamet.scalapb:protobuf-runtime-scala_sjs1_2.12:0.8.12
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localcom.thesamet.scalapb/protobuf-runtime-scala_sjs1_2.12/0.8.12/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/thesamet/scalapb/protobuf-runtime-scala_sjs1_2.12/0.8.12/protobuf-runtime-scala_sjs1_2.12-0.8.12.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/thesamet/scalapb/protobuf-runtime-scala_sjs1_2.12/0.8.12/protobuf-runtime-scala_sjs1_2.12-0.8.12.pom
```

**Comment by thesamet** [comment]
Actually none of the artifacts for 0.8.12 are available. I mistakenly tried to release `protobuf-runtime-scala` by directly pushing a tag to the repo instead of using `sbt-release`. Most of my repos were transitioned to sbt-ci-release, this one is behind on this... Anyway, I released v0.8.12 correctly now. It should be on maven shortly.

**Comment by thesamet** [comment]
🎉  Thank you!

**Pull request merged**
