### PR TITLE
add NotPreserveUnknownFields as GeneratorOption

### PR DESCRIPTION
**Pull request by alex-gaiduchok**
add NotPreserveUnknownFields as GeneratorOption

### CODE REVIEW

**Comment by thesamet** [comment]
Hi @alex-gaiduchok , thanks for sending this PR. We are refraining from adding new generator options that change the public API of the generated code since it breaks compatibility between ScalaPB plugins and leads to confusing developer experience. See this [FAQ](https://scalapb.github.io/docs/faq#why-a-certain-customization-is-not-available-as-a-global-generator-parameter) for more details. The recommended alternative for users is to use package-scoped options.

**Comment by alex-gaiduchok** [comment]
@thesamet thank you, was waiting for the response in gitter meanwhile added this draft) tbh its gonna be painful in my case cause proto files used not only by scala generator

**Comment by thesamet** [comment]
@alex-gaiduchok , in SBT you can add an additional directory to PB.protoSources just for the package-scoped options file, so your main protos directory isn't affected and other tools will not see it:

```
Compile / PB.protoSources += baseDirectory.value / "src"/ "main" / "scalapb-options"
```

**Comment by alex-gaiduchok** [comment]
> @alex-gaiduchok , in SBT you can add an additional directory to PB.protoSources just for the package-scoped options file, so your main protos directory isn't affected and other tools will not see it:
> 
> ```
> Compile / PB.protoSources += baseDirectory.value / "src"/ "main" / "scalapb-options"
> ```
> 
> Then place the package-scoped options file in `src/main/scalapb-options`.

Thanks, I'll give it a try =)

**Pull request closed without merging**
