### PR TITLE
Update to grpc to 1.51.1 and protobuf to 3.21.12

### PR DESCRIPTION
**Pull request by fsonntag**
Updating grpc-java and protobuf-java. 

Would be great if we can get a new release with the updated versions

### CODE REVIEW

**Comment by thesamet** [comment]
Please see #1454. For grpc-java, any specific reason you can't upgrade it within your project? Is there any feature you need from protobuf-java 3.21.x?

**Comment by fsonntag** [comment]
Ah, I see, thanks for getting back. Actually, I'm more keen on the GRPC update in order to have a newer `grpc-netty-shaded`, due to this issue:  
https://github.com/grpc/grpc-java/issues/8751

I'm not 100% sure if it was resolved with the newer version though

**Comment by thesamet** [comment]
It should be possible to bump up the version of `grpc-netty-shaded` as a dependency in your build without a new version of scalapb.

**Comment by fsonntag** [comment]
Yep, it is, I tried it! Was just worrying about conflicts appearing during runtime, so having the newer version in scalapb seems cleaner. But I'll with it for now, thanks a lot, @thesamet

**Pull request closed without merging**
