### PR TITLE
Allow sealed oneofs to be defined inside a parent message

### LINKED ISSUE #974: Allow sealed oneofs to be part of a parent message
This is a carry-on from #751. Might be niche use-case, but it would be nice to be able to define a `preamble` for the body of a generated companion object. The idea is to have messages, as well as sealed traits, namespaced to an enclosing object.

My use case is Akka Typed, particularly with persistence, where there is a naming-convention to have all the messages (the protocol) for an actor inside a single object, including a `sealed trait Command` and `Event`, which is then extended by messages.

My current solution is to hack the `sealed trait` preamble into the companion object using `annotations`

```proto
message SomeProtocol {
  message State {
    // Hack to place the sealed traits in the SomeProtocol object
    option (scalapb.message).annotations = "sealed trait Command";
    option (scalapb.message).annotations = "sealed trait Event";

    // ...
  }

  message DoSomething {
    option (scalapb.message).extends = "Command";
    // ...
  }

  message SomethingDone {
    option (scalapb.message).extends = "Event";
    // ...
  }
}
``` 

This way `SomeProtocol.Command` and `SomeProtocol.DoSomething` signal that they belong to the same "protocol" and belong to each other by living in the same object. They are also easily and idiomatically imported together using `import SomeProtocol._`.

### PR DESCRIPTION
**Pull request by otto-dev**
Closes #974

### CODE REVIEW

**Comment by thesamet** [comment]
Nice, thanks for working on this! Can you also add a test to e2e named something like `sealed_oneof_nested.proto` that test the new scenario?

**Comment by otto-dev** [comment]
Sure, let me have a look,

**Comment by otto-dev** [comment]
Okay, I've added the tests. Some may be redundant, and maybe you have a better idea of how to structure the test-file. Please let met know! Thanks

**Comment by thesamet** [comment]
LGTM - thanks for making this improvement!

**Comment by otto-dev** [comment]
No, thanks to you @thesamet for this library and your excellent maintenance of the same!

**Pull request merged**
