### PR TITLE
make generated companions extends FunctionN

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by thesamet** [comment]
What's the use case? Is it something everyone would need or better be a setting?

**Comment by xuwei-k** [comment]
A good use case is as follows;
Suppose we have `val foo: Option[String]` and a generated message `case class Bar(value: String) extends GeneratedMessage`, we can just write `foo.map(Bar)` instead of writing `foo.map(Bar(_))`. This results in shorter code, and what's more, we don't have to create unnecessary function objects.

**Comment by xuwei-k** [comment]
>  Is it something everyone would need or better be a setting?

I'll update to configurable.

**Comment by xuwei-k** [comment]
> > Is it something everyone would need or better be a setting?
> 
> I'll update to configurable.

done

**Comment by thesamet** [comment]
Seems like this would be mostly serving a style preference, since it's possible to write `foo.map(Bar.apply)` to avoid the creation of a function object. I would like to avoid the additional complexity. Closing the PR for now. I appreciate the time you took to write it, and will be happy to rethink this in the future if there's demand.

**Pull request closed without merging**
