### PR TITLE
Support scala 3.0.0-RC2

### PR DESCRIPTION
**Pull request by TimothyKlim**

### CODE REVIEW

**Comment by thesamet** [comment]
Note there's also #1113  - I haven't looked into the CI failures yet.

**Comment by TimothyKlim** [comment]
> Note there's also #1113 - I haven't looked into the CI failures yet.

Yeah, I know this. The difference between these two: sbt 1.5 without sbt-dotty (which deprecated now), fix transitive dependency of scala-xml.

**Comment by TimothyKlim** [comment]
I have another way to fix cross dependency issue with scala-xml:

```patch
-  private val exclRule =
-    ExclusionRule(organization = "org.scala-lang.modules") // Exclude scala-xml cross-version
-
-  val coursier  = "io.get-coursier"       %% "coursier"   % versions.coursier
-  val protocGen = ("com.thesamet.scalapb" %% "protoc-gen" % versions.protocGen).excludeAll(exclRule)
+  val coursier = "io.get-coursier" %% "coursier" % versions.coursier
+  val protocGen = ("com.thesamet.scalapb" %% "protoc-gen" % versions.protocGen)
+    .exclude(
+      "org.scala-lang.modules",
+      "scala-xml_2.13"
+    ) // https://github.com/scalatest/scalatest/issues/1973
   val protocCacheCoursier =
-    ("com.thesamet.scalapb" %% "protoc-cache-coursier" % versions.protocGen).excludeAll(exclRule)
+    ("com.thesamet.scalapb" %% "protoc-cache-coursier" % versions.protocGen)
+      .exclude(
+        "org.scala-lang.modules",
+        "scala-xml_2.13"
+      ) // https://github.com/scalatest/scalatest/issues/1973
```

**Comment by ahjohannessen** [comment]
👍

**Pull request merged**
