### PR TITLE
Downgrade to Scala 3.0.2 for compatibility reasons

### PR DESCRIPTION
**Pull request by anton-zen**

### CODE REVIEW

**Comment by thesamet** [comment]
Upgrades to this projects are done automatically by scala stewards. Can you look into scala stewards config file syntax for preventing for the version being bumped up again/

**Comment by anton-zen** [comment]
@thesamet This should do it. However, I haven't tested it as I am not sure how to do it locally.

**Comment by thesamet** [comment]
Looks like scala-stewards reverted this change: https://github.com/scalapb/ScalaPB/pull/1327 - can you revisit the ignore rules?

**Comment by anton-zen** [comment]
@thesamet Sure! Submitted a PR https://github.com/scalapb/ScalaPB/pull/1329

**Pull request merged**
